import {
  FaBell,
  FaComment,
  FaEnvelope,
  FaFacebook,
  FaInstagram,
} from "react-icons/fa";

export const campaignData = [
  {
    title: "Summer Collection Launch",
    channel: "Email",
    status: "Scheduled",
    scheduledFor: "June 15, 2025",
    targetAudience: "New Subscribers (24,568)",
    reach: null,
    opens: null,
    clicks: null,
    Icon: <FaEnvelope size={20} />,
  },
  {
    title: "Influencer Partnership",
    channel: "Social",
    status: "Active",
    started: "May 28, 2025",
    ends: "July 28, 2025",
    progress: 45,
    reach: "18.2K",
    engagement: "3.4K",
    conversions: 426,
    Icon: <FaInstagram size={20} />,
  },
  {
    title: "Flash Sale Notification",
    channel: "Push",
    status: "Draft",
    createdOn: "June 2, 2025",
    lastEdited: "June 8, 2025",
    reach: null,
    opens: null,
    clicks: null,
    Icon: <FaBell size={20} />,
  },
  {
    title: "Abandoned Cart Recovery",
    channel: "Email",
    status: "Active",
    started: "April 15, 2025",
    type: "Automated",
    performance: "+12.5% vs avg",
    performanceValue: 12.5,
    sent: 3842,
    opens: 2156,
    recovered: 684,
    Icon: <FaEnvelope size={20} />,
  },
  {
    title: "New Product Announcement",
    channel: "SMS",
    status: "Draft",
    createdOn: "June 5, 2025",
    targetAudience: "High-Value Shoppers (18,342)",
    reach: null,
    delivery: null,
    clicks: null,
    Icon: <FaComment size={20} />,
  },
  {
    title: "Holiday Season Promotion",
    channel: "Social",
    status: "Completed",
    started: "Dec 1, 2024",
    ended: "Dec 31, 2024",
    reach: "42.8K",
    engagement: "8.6K",
    conversions: 1248,
    Icon: <FaFacebook size={20} />,
  },
  {
    title: "Customer Feedback Survey",
    channel: "Email",
    status: "Scheduled",
    scheduledFor: "June 20, 2025",
    targetAudience: "Recent Purchasers (12,456)",
    reach: null,
    opens: null,
    responses: null,
    Icon: <FaComment size={20} />,
  },
  {
    title: "Back In Stock Alert",
    channel: "Push",
    status: "Paused",
    started: "May 12, 2025",
    pausedOn: "June 5, 2025",
    sent: 2456,
    opens: 1832,
    conversions: 342,
    Icon: <FaBell size={20} />,
  },
  {
    title: "Welcome Series",
    channel: "Email",
    status: "Active",
    started: "Jan 1, 2025",
    type: "Automated",
    performance: "+18.3% vs avg",
    performanceValue: 18.3,
    sent: 8456,
    opens: 6842,
    clicks: 3245,
    Icon: <FaEnvelope size={20} />,
  },
];
